### ISSUE TITLE
why does my aviutl show this??

### ISSUE THREAD

**Issue by nikitabaev71** [sevenc-nanashi/pjsekai-overlay#3]
![image](https://github.com/sevenc-nanashi/pjsekai-overlay/assets/130316254/e24bea56-cdb7-4c62-ae5c-595d9ff58724)

**Comment by sevenc-nanashi** [comment]
I can support pjsekai-overlay, but not AviUtl.
Also note that AviUtl is made for Japanese, not foreign users.
