### ISSUE TITLE
What does it mean?

### ISSUE THREAD

**Issue by Hanakohiraki** [sevenc-nanashi/pjsekai-overlay#7]
![สกรีนช็อต 2023-11-25 145153](https://github.com/sevenc-nanashi/pjsekai-overlay/assets/123821106/572c2f77-bba7-4e5c-a040-c9761f26fc6e)
![สกรีนช็อต 2023-11-25 145506](https://github.com/sevenc-nanashi/pjsekai-overlay/assets/123821106/158596e6-7391-4706-aa05-81d0e9deff98)

Why don't you record a video tutorial?

**Comment by sevenc-nanashi** [comment]
Read README
